db:
  image: postgres
web:
  build: .
  command: bundle exec guard
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
  volumes_from:
    - bundle
bundle:
  image: prelauncher_web
  volumes:
    - /bundle
